name: Check Repo2 Changes

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 * * * *'  # This runs the workflow every hour. Adjust the cron expression as needed.

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo1
        uses: actions/checkout@v2

      - name: Get the latest commit from repo2
        id: get_commit
        run: |
          echo "Fetching the latest commit details from repo2"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/JAYANTH-ORG/github-actions/commits/topic/init \
               > commit_details.json  # Replace 'main' with the branch you want to check
          echo "::set-output name=commit_details::$(cat commit_details.json)"

      - name: Check changed files
        run: |
          echo "Changed files in the latest commit:"
          jq '.files[].filename' commit_details.json
